CREATE TABLE IF NOT EXISTS `sb_neon_installs` (
  `plate`       VARCHAR(32) NOT NULL,
  `left_side`   TINYINT(1)  NOT NULL DEFAULT 0,
  `right_side`  TINYINT(1)  NOT NULL DEFAULT 0,
  `front_side`  TINYINT(1)  NOT NULL DEFAULT 0,
  `back_side`   TINYINT(1)  NOT NULL DEFAULT 0,
  `updated_at`  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`plate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
